sudo: false
language: ruby
rvm:
  - 2.5.5
  - 2.6.2
  - ruby-head
env:
  - RUBY_VERSION_FOR_DEPLOY=2.6.2
branches:
  only:
    - master
cache: bundler
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - travis_retry bundle install --jobs=3 --retry=3
  - bundle exec jekyll build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: _site
  target-branch: gh-pages
  fqdn: virtualspirit.github.io
  on:
    branch: master
    rvm: $RUBY_VERSION_FOR_DEPLOY
notifications:
  email: false
